//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AITS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmpId { get; set; }
        [Required]
        [Display(Name = "First Name")]
        [StringLength(50,ErrorMessage="Max Length upto 50 Characters")]
        //[RegularExpression("^[A-Za-z]$", ErrorMessage = "Only alphabet characters are allowed")]
        public string Fname { get; set; }
        [Display(Name = "Middle Name")]
        //[RegularExpression("^[A-Za-z]$", ErrorMessage = "Only alphabet characters are allowed")]
        public string Mname { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        //[RegularExpression("^[A-Za-z]$", ErrorMessage = "Only alphabet characters are allowed")]
        public string Lname { get; set; }
        [Required]
        [Display(Name = "Department")]
        public Nullable<int> DeptId { get; set; }
        [Required]
        [Display(Name = "Designation")]
        public Nullable<int> DesgId { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "Max Length upto 50 Characters")]
        public string Supervisor { get; set; }
        [Required]
        [Display(Name = "Date of Joining")]
        [RegularExpression("^\\d{2}-\\d{2}-\\d{4}$", ErrorMessage = "Please Enter Valid Date (eg. 01-01-2020")]
        public string DOJ { get; set; }
        [Required]
        [Display(Name = "Email Address")]
        [RegularExpression("^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$", ErrorMessage = "Please Enter Valid Email")]
        public string Email { get; set; }
        [Display(Name = "Cell No")]
        [RegularExpression("^\\d{10}$", ErrorMessage = "Please Enter Valid Phone Number")]
        public string Cell { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
    }
}
